/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as CollageMakerRouteImport } from './routes/collage-maker'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImageToTextRouteImport } from './routes/image-to-text'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PdfMergerRouteImport } from './routes/pdf-merger'
import { Route as PdfToPptxRouteImport } from './routes/pdf-to-pptx'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RemoveTextRouteImport } from './routes/remove-text'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiExtractTextRouteImport } from './routes/api/extract-text'
import { Route as ApiMergePdfRouteImport } from './routes/api/merge-pdf'
import { Route as ApiPdfMergeRouteImport } from './routes/api/pdf-merge'
import { Route as ApiPdfToPptxRouteImport } from './routes/api/pdf-to-pptx'
import { Route as ApiPdfToWordRouteImport } from './routes/api/pdf-to-word'
import { Route as ApiRemoveTextRouteImport } from './routes/api/remove-text'
import { Route as ApiResetPasswordRouteImport } from './routes/api/reset-password'
import { Route as ApiSnapyAskRouteImport } from './routes/api/snapy-ask'
import { Route as ApiSnapyEditRouteImport } from './routes/api/snapy-edit'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const CollageMakerRoute = CollageMakerRouteImport.update({
  id: '/collage-maker',
  path: '/collage-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToTextRoute = ImageToTextRouteImport.update({
  id: '/image-to-text',
  path: '/image-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfMergerRoute = PdfMergerRouteImport.update({
  id: '/pdf-merger',
  path: '/pdf-merger',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPptxRoute = PdfToPptxRouteImport.update({
  id: '/pdf-to-pptx',
  path: '/pdf-to-pptx',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveTextRoute = RemoveTextRouteImport.update({
  id: '/remove-text',
  path: '/remove-text',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractTextRoute = ApiExtractTextRouteImport.update({
  id: '/api/extract-text',
  path: '/api/extract-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMergePdfRoute = ApiMergePdfRouteImport.update({
  id: '/api/merge-pdf',
  path: '/api/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfMergeRoute = ApiPdfMergeRouteImport.update({
  id: '/api/pdf-merge',
  path: '/api/pdf-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfToPptxRoute = ApiPdfToPptxRouteImport.update({
  id: '/api/pdf-to-pptx',
  path: '/api/pdf-to-pptx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfToWordRoute = ApiPdfToWordRouteImport.update({
  id: '/api/pdf-to-word',
  path: '/api/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveTextRoute = ApiRemoveTextRouteImport.update({
  id: '/api/remove-text',
  path: '/api/remove-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetPasswordRoute = ApiResetPasswordRouteImport.update({
  id: '/api/reset-password',
  path: '/api/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapyAskRoute = ApiSnapyAskRouteImport.update({
  id: '/api/snapy-ask',
  path: '/api/snapy-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapyEditRoute = ApiSnapyEditRouteImport.update({
  id: '/api/snapy-edit',
  path: '/api/snapy-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/collage-maker': typeof CollageMakerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/pdf-merger': typeof PdfMergerRoute
  '/pdf-to-pptx': typeof PdfToPptxRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/pricing': typeof PricingRoute
  '/remove-text': typeof RemoveTextRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/extract-text': typeof ApiExtractTextRoute
  '/api/merge-pdf': typeof ApiMergePdfRoute
  '/api/pdf-merge': typeof ApiPdfMergeRoute
  '/api/pdf-to-pptx': typeof ApiPdfToPptxRoute
  '/api/pdf-to-word': typeof ApiPdfToWordRoute
  '/api/remove-text': typeof ApiRemoveTextRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/snapy-ask': typeof ApiSnapyAskRoute
  '/api/snapy-edit': typeof ApiSnapyEditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/collage-maker': typeof CollageMakerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/pdf-merger': typeof PdfMergerRoute
  '/pdf-to-pptx': typeof PdfToPptxRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/pricing': typeof PricingRoute
  '/remove-text': typeof RemoveTextRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/extract-text': typeof ApiExtractTextRoute
  '/api/merge-pdf': typeof ApiMergePdfRoute
  '/api/pdf-merge': typeof ApiPdfMergeRoute
  '/api/pdf-to-pptx': typeof ApiPdfToPptxRoute
  '/api/pdf-to-word': typeof ApiPdfToWordRoute
  '/api/remove-text': typeof ApiRemoveTextRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/snapy-ask': typeof ApiSnapyAskRoute
  '/api/snapy-edit': typeof ApiSnapyEditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/collage-maker': typeof CollageMakerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/pdf-merger': typeof PdfMergerRoute
  '/pdf-to-pptx': typeof PdfToPptxRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/pricing': typeof PricingRoute
  '/remove-text': typeof RemoveTextRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/extract-text': typeof ApiExtractTextRoute
  '/api/merge-pdf': typeof ApiMergePdfRoute
  '/api/pdf-merge': typeof ApiPdfMergeRoute
  '/api/pdf-to-pptx': typeof ApiPdfToPptxRoute
  '/api/pdf-to-word': typeof ApiPdfToWordRoute
  '/api/remove-text': typeof ApiRemoveTextRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/snapy-ask': typeof ApiSnapyAskRoute
  '/api/snapy-edit': typeof ApiSnapyEditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/collage-maker'
    | '/dashboard'
    | '/history'
    | '/image-to-text'
    | '/login'
    | '/pdf-merger'
    | '/pdf-to-pptx'
    | '/pdf-to-word'
    | '/pricing'
    | '/remove-text'
    | '/settings'
    | '/signup'
    | '/api/extract-text'
    | '/api/merge-pdf'
    | '/api/pdf-merge'
    | '/api/pdf-to-pptx'
    | '/api/pdf-to-word'
    | '/api/remove-text'
    | '/api/reset-password'
    | '/api/snapy-ask'
    | '/api/snapy-edit'
    | '/auth/callback'
    | '/auth/update-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/collage-maker'
    | '/dashboard'
    | '/history'
    | '/image-to-text'
    | '/login'
    | '/pdf-merger'
    | '/pdf-to-pptx'
    | '/pdf-to-word'
    | '/pricing'
    | '/remove-text'
    | '/settings'
    | '/signup'
    | '/api/extract-text'
    | '/api/merge-pdf'
    | '/api/pdf-merge'
    | '/api/pdf-to-pptx'
    | '/api/pdf-to-word'
    | '/api/remove-text'
    | '/api/reset-password'
    | '/api/snapy-ask'
    | '/api/snapy-edit'
    | '/auth/callback'
    | '/auth/update-password'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/collage-maker'
    | '/dashboard'
    | '/history'
    | '/image-to-text'
    | '/login'
    | '/pdf-merger'
    | '/pdf-to-pptx'
    | '/pdf-to-word'
    | '/pricing'
    | '/remove-text'
    | '/settings'
    | '/signup'
    | '/api/extract-text'
    | '/api/merge-pdf'
    | '/api/pdf-merge'
    | '/api/pdf-to-pptx'
    | '/api/pdf-to-word'
    | '/api/remove-text'
    | '/api/reset-password'
    | '/api/snapy-ask'
    | '/api/snapy-edit'
    | '/auth/callback'
    | '/auth/update-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  CollageMakerRoute: typeof CollageMakerRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  ImageToTextRoute: typeof ImageToTextRoute
  LoginRoute: typeof LoginRoute
  PdfMergerRoute: typeof PdfMergerRoute
  PdfToPptxRoute: typeof PdfToPptxRoute
  PdfToWordRoute: typeof PdfToWordRoute
  PricingRoute: typeof PricingRoute
  RemoveTextRoute: typeof RemoveTextRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ApiExtractTextRoute: typeof ApiExtractTextRoute
  ApiMergePdfRoute: typeof ApiMergePdfRoute
  ApiPdfMergeRoute: typeof ApiPdfMergeRoute
  ApiPdfToPptxRoute: typeof ApiPdfToPptxRoute
  ApiPdfToWordRoute: typeof ApiPdfToWordRoute
  ApiRemoveTextRoute: typeof ApiRemoveTextRoute
  ApiResetPasswordRoute: typeof ApiResetPasswordRoute
  ApiSnapyAskRoute: typeof ApiSnapyAskRoute
  ApiSnapyEditRoute: typeof ApiSnapyEditRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collage-maker': {
      id: '/collage-maker'
      path: '/collage-maker'
      fullPath: '/collage-maker'
      preLoaderRoute: typeof CollageMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-text': {
      id: '/image-to-text'
      path: '/image-to-text'
      fullPath: '/image-to-text'
      preLoaderRoute: typeof ImageToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-merger': {
      id: '/pdf-merger'
      path: '/pdf-merger'
      fullPath: '/pdf-merger'
      preLoaderRoute: typeof PdfMergerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-pptx': {
      id: '/pdf-to-pptx'
      path: '/pdf-to-pptx'
      fullPath: '/pdf-to-pptx'
      preLoaderRoute: typeof PdfToPptxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-text': {
      id: '/remove-text'
      path: '/remove-text'
      fullPath: '/remove-text'
      preLoaderRoute: typeof RemoveTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-text': {
      id: '/api/extract-text'
      path: '/api/extract-text'
      fullPath: '/api/extract-text'
      preLoaderRoute: typeof ApiExtractTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merge-pdf': {
      id: '/api/merge-pdf'
      path: '/api/merge-pdf'
      fullPath: '/api/merge-pdf'
      preLoaderRoute: typeof ApiMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-merge': {
      id: '/api/pdf-merge'
      path: '/api/pdf-merge'
      fullPath: '/api/pdf-merge'
      preLoaderRoute: typeof ApiPdfMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-to-pptx': {
      id: '/api/pdf-to-pptx'
      path: '/api/pdf-to-pptx'
      fullPath: '/api/pdf-to-pptx'
      preLoaderRoute: typeof ApiPdfToPptxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-to-word': {
      id: '/api/pdf-to-word'
      path: '/api/pdf-to-word'
      fullPath: '/api/pdf-to-word'
      preLoaderRoute: typeof ApiPdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-text': {
      id: '/api/remove-text'
      path: '/api/remove-text'
      fullPath: '/api/remove-text'
      preLoaderRoute: typeof ApiRemoveTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset-password': {
      id: '/api/reset-password'
      path: '/api/reset-password'
      fullPath: '/api/reset-password'
      preLoaderRoute: typeof ApiResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapy-ask': {
      id: '/api/snapy-ask'
      path: '/api/snapy-ask'
      fullPath: '/api/snapy-ask'
      preLoaderRoute: typeof ApiSnapyAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapy-edit': {
      id: '/api/snapy-edit'
      path: '/api/snapy-edit'
      fullPath: '/api/snapy-edit'
      preLoaderRoute: typeof ApiSnapyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  CollageMakerRoute: CollageMakerRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  ImageToTextRoute: ImageToTextRoute,
  LoginRoute: LoginRoute,
  PdfMergerRoute: PdfMergerRoute,
  PdfToPptxRoute: PdfToPptxRoute,
  PdfToWordRoute: PdfToWordRoute,
  PricingRoute: PricingRoute,
  RemoveTextRoute: RemoveTextRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ApiExtractTextRoute: ApiExtractTextRoute,
  ApiMergePdfRoute: ApiMergePdfRoute,
  ApiPdfMergeRoute: ApiPdfMergeRoute,
  ApiPdfToPptxRoute: ApiPdfToPptxRoute,
  ApiPdfToWordRoute: ApiPdfToWordRoute,
  ApiRemoveTextRoute: ApiRemoveTextRoute,
  ApiResetPasswordRoute: ApiResetPasswordRoute,
  ApiSnapyAskRoute: ApiSnapyAskRoute,
  ApiSnapyEditRoute: ApiSnapyEditRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
