/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as RecoveryCodesRouteImport } from './routes/recovery-codes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TotpSetupRouteImport } from './routes/totp-setup'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCodesRoute = RecoveryCodesRouteImport.update({
  id: '/recovery-codes',
  path: '/recovery-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpSetupRoute = TotpSetupRouteImport.update({
  id: '/totp-setup',
  path: '/totp-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recovery-codes': typeof RecoveryCodesRoute
  '/register': typeof RegisterRoute
  '/totp-setup': typeof TotpSetupRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recovery-codes': typeof RecoveryCodesRoute
  '/register': typeof RegisterRoute
  '/totp-setup': typeof TotpSetupRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recovery-codes': typeof RecoveryCodesRoute
  '/register': typeof RegisterRoute
  '/totp-setup': typeof TotpSetupRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/recovery-codes'
    | '/register'
    | '/totp-setup'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/recovery-codes'
    | '/register'
    | '/totp-setup'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/recovery-codes'
    | '/register'
    | '/totp-setup'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RecoveryCodesRoute: typeof RecoveryCodesRoute
  RegisterRoute: typeof RegisterRoute
  TotpSetupRoute: typeof TotpSetupRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-codes': {
      id: '/recovery-codes'
      path: '/recovery-codes'
      fullPath: '/recovery-codes'
      preLoaderRoute: typeof RecoveryCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp-setup': {
      id: '/totp-setup'
      path: '/totp-setup'
      fullPath: '/totp-setup'
      preLoaderRoute: typeof TotpSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  RecoveryCodesRoute: RecoveryCodesRoute,
  RegisterRoute: RegisterRoute,
  TotpSetupRoute: TotpSetupRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
